/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowDigitizationRouteImport } from './routes/workflow-digitization'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as OperationalSystemsRouteImport } from './routes/operational-systems'
import { Route as ManagedServicesRouteImport } from './routes/managed-services'
import { Route as LegacyModernizationRouteImport } from './routes/legacy-modernization'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowDigitizationRoute = WorkflowDigitizationRouteImport.update({
  id: '/workflow-digitization',
  path: '/workflow-digitization',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationalSystemsRoute = OperationalSystemsRouteImport.update({
  id: '/operational-systems',
  path: '/operational-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagedServicesRoute = ManagedServicesRouteImport.update({
  id: '/managed-services',
  path: '/managed-services',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyModernizationRoute = LegacyModernizationRouteImport.update({
  id: '/legacy-modernization',
  path: '/legacy-modernization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/legacy-modernization': typeof LegacyModernizationRoute
  '/managed-services': typeof ManagedServicesRoute
  '/operational-systems': typeof OperationalSystemsRoute
  '/overview': typeof OverviewRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
  '/workflow-digitization': typeof WorkflowDigitizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/legacy-modernization': typeof LegacyModernizationRoute
  '/managed-services': typeof ManagedServicesRoute
  '/operational-systems': typeof OperationalSystemsRoute
  '/overview': typeof OverviewRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
  '/workflow-digitization': typeof WorkflowDigitizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/legacy-modernization': typeof LegacyModernizationRoute
  '/managed-services': typeof ManagedServicesRoute
  '/operational-systems': typeof OperationalSystemsRoute
  '/overview': typeof OverviewRoute
  '/services': typeof ServicesRoute
  '/why-us': typeof WhyUsRoute
  '/workflow-digitization': typeof WorkflowDigitizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/legacy-modernization'
    | '/managed-services'
    | '/operational-systems'
    | '/overview'
    | '/services'
    | '/why-us'
    | '/workflow-digitization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/legacy-modernization'
    | '/managed-services'
    | '/operational-systems'
    | '/overview'
    | '/services'
    | '/why-us'
    | '/workflow-digitization'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/legacy-modernization'
    | '/managed-services'
    | '/operational-systems'
    | '/overview'
    | '/services'
    | '/why-us'
    | '/workflow-digitization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  LegacyModernizationRoute: typeof LegacyModernizationRoute
  ManagedServicesRoute: typeof ManagedServicesRoute
  OperationalSystemsRoute: typeof OperationalSystemsRoute
  OverviewRoute: typeof OverviewRoute
  ServicesRoute: typeof ServicesRoute
  WhyUsRoute: typeof WhyUsRoute
  WorkflowDigitizationRoute: typeof WorkflowDigitizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow-digitization': {
      id: '/workflow-digitization'
      path: '/workflow-digitization'
      fullPath: '/workflow-digitization'
      preLoaderRoute: typeof WorkflowDigitizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operational-systems': {
      id: '/operational-systems'
      path: '/operational-systems'
      fullPath: '/operational-systems'
      preLoaderRoute: typeof OperationalSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managed-services': {
      id: '/managed-services'
      path: '/managed-services'
      fullPath: '/managed-services'
      preLoaderRoute: typeof ManagedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy-modernization': {
      id: '/legacy-modernization'
      path: '/legacy-modernization'
      fullPath: '/legacy-modernization'
      preLoaderRoute: typeof LegacyModernizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  LegacyModernizationRoute: LegacyModernizationRoute,
  ManagedServicesRoute: ManagedServicesRoute,
  OperationalSystemsRoute: OperationalSystemsRoute,
  OverviewRoute: OverviewRoute,
  ServicesRoute: ServicesRoute,
  WhyUsRoute: WhyUsRoute,
  WorkflowDigitizationRoute: WorkflowDigitizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
